### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by levinsonmm** [levinsonmm/MI-449-SS17-741-html-meta-elements-_f2DoK#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://levins23-kapv98gmwdanx_f2dok.surge.sh/) and meets the following criteria:

- [x] Include a homepage and at least one other page, for your best-selling T-shirt (you can download a T-shirt image [from ThinkGeek](http://www.thinkgeek.com/clothing/t-shirts/))
- [x] A language is specified for the website (it does _not_ have to be in English!)
- [x] A `title` and `meta name="description"` are provided for each page
- [x] Every page includes a link to a `favicon.ico` file with the company logo (you can [create one here](https://www.hipsterlogogenerator.com/) or design one yourself)
- [x] Location information is provided on every page (you can place the store anywhere in the world, as long as there's an existing building there)
- [x] When each page is shared on Facebook and Twitter, a beautiful card is generated (and the [respective](https://developers.facebook.com/tools/debug/sharing/) [validators](https://cards-dev.twitter.com/validator) should return no errors/warnings -- though you can ignore the `Share App ID Missing` warning for Facebook)

**Comment by KatieMFritz** [comment]
I'm not seeing your project on surge. Are you??

**Comment by levinsonmm** [comment]
My bad! I pushed it to gh-pages instead of surge. Should be on surge now!

**Comment by KatieMFritz** [comment]
Great job! 👕 👍 🌟 

Only one small thing to change.

### Location
I see `geo.position`, but not ICBM. [From the lesson](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/html-meta-elements/3):
> Even though they'll provide the same information, it's good to include both of these elements, because some services might look for one, but not the other.

**Comment by levinsonmm** [comment]
Got it! I added an ICBM element.

**Comment by KatieMFritz** [comment]
<img src="http://i86.photobucket.com/albums/k116/sparky710/PGPrincess%20Stuff/Cats/HighFiveCat.jpg" alt="high five cat">

:shipit:
